apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nizar-nginx
spec:
  source:
    type: Git
    git:
      uri: "https://github.com/Shintai-X/openshift-demo.git"
      ref: main
    contextDir: ""
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: "nginx:latest"
  triggers:
    - type: ConfigChange
    - type: ImageChange
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ""
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - nginx
        from:
          kind: ImageStreamTag
          name: nginx:latest
strategy:
  type: Recreate
  recreateParams:
    timeoutSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx
spec:
  host: testing-route.apps-crc.testing
  to:
    kind: Service
    name: nginx
  port:
    targetPort: http
  tls:
    termination: edge
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nginx
spec:
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: nginxinc/nginx-unprivileged:1.25
      importPolicy:
        scheduled: true
